### ISSUE TITLE
Plugin errors when exporting an image with multiple layers.

### ISSUE THREAD

**Issue by colorworm** [chausner/gimp-jxr#1]
Hi,

Prior to the rewrite, the plugin had no problems exporting multi-layered images (using GIMPJPEGXRPlugin 1.0.1) as a .jxr. With the release of the rewrite, however, the plugin throws an error whenever the image I'm exporting has multiple layers.

A screenshot of the error:
![error](https://user-images.githubusercontent.com/29527070/27265443-09daa78c-5464-11e7-9a71-1cfac317f5b8.png)

I'm on a Windows 7 install running GIMP 2.8.22 in conjunction to gimp-jxr 2.1.

**Comment by chausner** [comment]
Thanks for reporting the issue but I haven't been able to reproduce it, yet. Does the error occur with [this multi-layered image](https://github.com/Stunning/gimp-export-layers-to-css/blob/master/sample/sample.xcf)? If not, can you upload a sample image which reproduces the issue for you? Thanks.

**Comment by colorworm** [comment]
I encountered the very same error with the sample image you provided.

By the way, I forgot to mention that the plugin does work -- I'm able to successfully export multi-layered images as .jxrs and open said .jxrs successfully in an image viewer -- it's just that whenever I export the images, the error pops up.

The error itself doesn't seem to be hindering the export process, but it is still mildly annoying to deal with.

**Comment by chausner** [comment]
I was able to reproduce the issue now. Version 2.1.1 fixes it.
